try {
    let x = y + 10;
}
catch(error) {
    console.log("An error occured:", error.message);
}